### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by muv1** [MikielAgutu/typ-site#2]
Where is the source code for the actual program?

**Comment by MikielAgutu** [comment]
Thanks for your interest in Typ :)

Typ is currently closed source. Is there any particular reason you'd like to see the source code?

**Comment by muv1** [comment]
I only use open source software, with few exceptions.

**Comment by muv1** [comment]
I ended up using this for my needs:

<https://github.com/dompdf/dompdf>

I found that in general Markdown is not a good format to convert to PDF, as it
doesnt have native CSS support.
